server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.17.92:3306/springcloud?useUnicode=true&amp;amp;characterEncoding=UTF-8
    username: test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver